name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # python-version: [3.12, 3.13]
        python-version: [3.13]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install requirements
        run: python3 -m pip install -r dev-requirements.txt

      - name: Run pytest
        run: python3 -m pytest

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip

      - name: Install requirements
        run: python3 -m pip install -r dev-requirements.txt

      - name: Lint
        run: python3 -m ruff check .

      - name: Format
        run: python3 -m ruff format . --check
